sudo: true
language: node_js
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
node_js:
  - '8'
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install -g jest codecov
script:
  - npm run test
after_success:
  - codecov
